name: Deploy Backend para Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        working-directory: ./backend
        run: npm install

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: clinica-backend-app-dev-account
          slot-name: production
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./backend
